# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QDoubleSpinBox,
    QFormLayout, QFrame, QGridLayout, QGroupBox,
    QHeaderView, QLabel, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QTableWidget,
    QTableWidgetItem, QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1269, 1125)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        MainWindow.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setFamilies([u"Cascadia Mono"])
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setBaseSize(QSize(0, 0))
        self.centralwidget.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setMaximumSize(QSize(16777215, 16777215))
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1251, 1107))
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.group_button = QGroupBox(self.scrollAreaWidgetContents)
        self.group_button.setObjectName(u"group_button")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.group_button.sizePolicy().hasHeightForWidth())
        self.group_button.setSizePolicy(sizePolicy2)
        self.group_button.setMinimumSize(QSize(0, 0))
        self.group_button.setMaximumSize(QSize(326, 296))
        self.group_button.setBaseSize(QSize(371, 511))
        self.gridLayout_3 = QGridLayout(self.group_button)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.button_disconnect = QPushButton(self.group_button)
        self.button_disconnect.setObjectName(u"button_disconnect")
        sizePolicy.setHeightForWidth(self.button_disconnect.sizePolicy().hasHeightForWidth())
        self.button_disconnect.setSizePolicy(sizePolicy)
        self.button_disconnect.setMinimumSize(QSize(149, 60))
        self.button_disconnect.setMaximumSize(QSize(150, 60))
        self.button_disconnect.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_disconnect, 0, 1, 1, 1)

        self.button_connect = QPushButton(self.group_button)
        self.button_connect.setObjectName(u"button_connect")
        sizePolicy.setHeightForWidth(self.button_connect.sizePolicy().hasHeightForWidth())
        self.button_connect.setSizePolicy(sizePolicy)
        self.button_connect.setMinimumSize(QSize(133, 60))
        self.button_connect.setMaximumSize(QSize(150, 60))
        self.button_connect.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_connect, 0, 0, 1, 1)

        self.button_takeoff = QPushButton(self.group_button)
        self.button_takeoff.setObjectName(u"button_takeoff")
        sizePolicy.setHeightForWidth(self.button_takeoff.sizePolicy().hasHeightForWidth())
        self.button_takeoff.setSizePolicy(sizePolicy)
        self.button_takeoff.setMinimumSize(QSize(133, 60))
        self.button_takeoff.setMaximumSize(QSize(150, 60))
        self.button_takeoff.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_takeoff, 1, 0, 1, 1)

        self.button_fly = QPushButton(self.group_button)
        self.button_fly.setObjectName(u"button_fly")
        sizePolicy.setHeightForWidth(self.button_fly.sizePolicy().hasHeightForWidth())
        self.button_fly.setSizePolicy(sizePolicy)
        self.button_fly.setMinimumSize(QSize(133, 60))
        self.button_fly.setMaximumSize(QSize(150, 60))
        self.button_fly.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_fly, 2, 0, 1, 1)

        self.button_reset = QPushButton(self.group_button)
        self.button_reset.setObjectName(u"button_reset")
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setMinimumSize(QSize(133, 60))
        self.button_reset.setMaximumSize(QSize(150, 60))
        self.button_reset.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_reset, 3, 0, 1, 1)

        self.button_hover = QPushButton(self.group_button)
        self.button_hover.setObjectName(u"button_hover")
        sizePolicy.setHeightForWidth(self.button_hover.sizePolicy().hasHeightForWidth())
        self.button_hover.setSizePolicy(sizePolicy)
        self.button_hover.setMinimumSize(QSize(149, 60))
        self.button_hover.setMaximumSize(QSize(150, 60))
        self.button_hover.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_hover, 2, 1, 1, 1)

        self.button_land = QPushButton(self.group_button)
        self.button_land.setObjectName(u"button_land")
        sizePolicy.setHeightForWidth(self.button_land.sizePolicy().hasHeightForWidth())
        self.button_land.setSizePolicy(sizePolicy)
        self.button_land.setMinimumSize(QSize(149, 60))
        self.button_land.setMaximumSize(QSize(150, 60))
        self.button_land.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout_3.addWidget(self.button_land, 1, 1, 1, 1)


        self.gridLayout_2.addWidget(self.group_button, 3, 3, 1, 1)

        self.group_plot = QGroupBox(self.scrollAreaWidgetContents)
        self.group_plot.setObjectName(u"group_plot")
        sizePolicy.setHeightForWidth(self.group_plot.sizePolicy().hasHeightForWidth())
        self.group_plot.setSizePolicy(sizePolicy)
        self.group_plot.setMinimumSize(QSize(0, 0))
        self.group_plot.setMaximumSize(QSize(16557, 16557))
        self.group_plot.setBaseSize(QSize(841, 841))
        self.gridLayout_plot = QGridLayout(self.group_plot)
        self.gridLayout_plot.setObjectName(u"gridLayout_plot")

        self.gridLayout_2.addWidget(self.group_plot, 1, 0, 3, 3)

        self.groupBox = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QSize(0, 300))
        self.groupBox.setMaximumSize(QSize(16777215, 350))
        self.gridLayout_5 = QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.text_log = QTextBrowser(self.groupBox)
        self.text_log.setObjectName(u"text_log")
        self.text_log.setFrameShape(QFrame.NoFrame)
        self.text_log.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.text_log.setAutoFormatting(QTextEdit.AutoNone)
        self.text_log.setLineWrapMode(QTextEdit.WidgetWidth)
        self.text_log.setLineWrapColumnOrWidth(4)
        self.text_log.setAcceptRichText(False)

        self.gridLayout_5.addWidget(self.text_log, 0, 0, 1, 1)


        self.gridLayout_2.addWidget(self.groupBox, 0, 2, 1, 2)

        self.group_telemetry = QGroupBox(self.scrollAreaWidgetContents)
        self.group_telemetry.setObjectName(u"group_telemetry")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.group_telemetry.sizePolicy().hasHeightForWidth())
        self.group_telemetry.setSizePolicy(sizePolicy3)
        self.group_telemetry.setMinimumSize(QSize(0, 0))
        self.group_telemetry.setMaximumSize(QSize(326, 16557))
        self.group_telemetry.setBaseSize(QSize(371, 521))
        self.group_telemetry.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.gridLayout_4 = QGridLayout(self.group_telemetry)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.table_telemetry = QTableWidget(self.group_telemetry)
        if (self.table_telemetry.columnCount() < 2):
            self.table_telemetry.setColumnCount(2)
        if (self.table_telemetry.rowCount() < 10):
            self.table_telemetry.setRowCount(10)
        self.table_telemetry.setObjectName(u"table_telemetry")
        sizePolicy.setHeightForWidth(self.table_telemetry.sizePolicy().hasHeightForWidth())
        self.table_telemetry.setSizePolicy(sizePolicy)
        self.table_telemetry.setMinimumSize(QSize(288, 366))
        self.table_telemetry.setFrameShape(QFrame.NoFrame)
        self.table_telemetry.setAlternatingRowColors(True)
        self.table_telemetry.setShowGrid(False)
        self.table_telemetry.setGridStyle(Qt.NoPen)
        self.table_telemetry.setWordWrap(True)
        self.table_telemetry.setRowCount(10)
        self.table_telemetry.setColumnCount(2)
        self.table_telemetry.horizontalHeader().setVisible(True)
        self.table_telemetry.horizontalHeader().setCascadingSectionResizes(False)
        self.table_telemetry.horizontalHeader().setMinimumSectionSize(60)
        self.table_telemetry.horizontalHeader().setDefaultSectionSize(100)
        self.table_telemetry.horizontalHeader().setProperty("showSortIndicator", False)
        self.table_telemetry.horizontalHeader().setStretchLastSection(True)
        self.table_telemetry.verticalHeader().setVisible(False)
        self.table_telemetry.verticalHeader().setStretchLastSection(False)

        self.gridLayout_4.addWidget(self.table_telemetry, 0, 0, 1, 1)


        self.gridLayout_2.addWidget(self.group_telemetry, 1, 3, 1, 1)

        self.group_continous_motion = QGroupBox(self.scrollAreaWidgetContents)
        self.group_continous_motion.setObjectName(u"group_continous_motion")
        sizePolicy3.setHeightForWidth(self.group_continous_motion.sizePolicy().hasHeightForWidth())
        self.group_continous_motion.setSizePolicy(sizePolicy3)
        self.group_continous_motion.setMinimumSize(QSize(0, 300))
        self.group_continous_motion.setMaximumSize(QSize(300, 350))
        self.group_continous_motion.setBaseSize(QSize(302, 221))
        self.group_continous_motion.setCheckable(True)
        self.group_continous_motion.setChecked(False)
        self.formLayout = QFormLayout(self.group_continous_motion)
        self.formLayout.setObjectName(u"formLayout")
        self.label_15 = QLabel(self.group_continous_motion)
        self.label_15.setObjectName(u"label_15")
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QSize(0, 0))
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_15)

        self.label_19 = QLabel(self.group_continous_motion)
        self.label_19.setObjectName(u"label_19")
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QSize(0, 0))
        self.label_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_19)

        self.label_16 = QLabel(self.group_continous_motion)
        self.label_16.setObjectName(u"label_16")
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QSize(0, 0))
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_16)

        self.label_17 = QLabel(self.group_continous_motion)
        self.label_17.setObjectName(u"label_17")
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QSize(0, 0))
        self.label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_17)

        self.label_18 = QLabel(self.group_continous_motion)
        self.label_18.setObjectName(u"label_18")
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QSize(0, 0))
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_18)

        self.label_20 = QLabel(self.group_continous_motion)
        self.label_20.setObjectName(u"label_20")
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QSize(0, 0))
        self.label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.label_20)

        self.label_21 = QLabel(self.group_continous_motion)
        self.label_21.setObjectName(u"label_21")
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QSize(0, 0))

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.label_21)

        self.label_22 = QLabel(self.group_continous_motion)
        self.label_22.setObjectName(u"label_22")
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QSize(0, 0))

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.label_22)

        self.input_velocity_forward = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_forward.setObjectName(u"input_velocity_forward")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.input_velocity_forward.sizePolicy().hasHeightForWidth())
        self.input_velocity_forward.setSizePolicy(sizePolicy4)
        self.input_velocity_forward.setMinimumSize(QSize(0, 30))
        self.input_velocity_forward.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_forward.setAlignment(Qt.AlignCenter)
        self.input_velocity_forward.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_forward.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_forward.setProperty("showGroupSeparator", False)
        self.input_velocity_forward.setMaximum(1.000000000000000)
        self.input_velocity_forward.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.input_velocity_forward)

        self.input_velocity_left = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_left.setObjectName(u"input_velocity_left")
        sizePolicy4.setHeightForWidth(self.input_velocity_left.sizePolicy().hasHeightForWidth())
        self.input_velocity_left.setSizePolicy(sizePolicy4)
        self.input_velocity_left.setMinimumSize(QSize(0, 30))
        self.input_velocity_left.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_left.setAlignment(Qt.AlignCenter)
        self.input_velocity_left.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_left.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_left.setProperty("showGroupSeparator", False)
        self.input_velocity_left.setMaximum(1.000000000000000)
        self.input_velocity_left.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.input_velocity_left)

        self.input_velocity_right = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_right.setObjectName(u"input_velocity_right")
        sizePolicy4.setHeightForWidth(self.input_velocity_right.sizePolicy().hasHeightForWidth())
        self.input_velocity_right.setSizePolicy(sizePolicy4)
        self.input_velocity_right.setMinimumSize(QSize(0, 30))
        self.input_velocity_right.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_right.setAlignment(Qt.AlignCenter)
        self.input_velocity_right.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_right.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_right.setProperty("showGroupSeparator", False)
        self.input_velocity_right.setMaximum(1.000000000000000)
        self.input_velocity_right.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.input_velocity_right)

        self.input_velocity_back = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_back.setObjectName(u"input_velocity_back")
        sizePolicy4.setHeightForWidth(self.input_velocity_back.sizePolicy().hasHeightForWidth())
        self.input_velocity_back.setSizePolicy(sizePolicy4)
        self.input_velocity_back.setMinimumSize(QSize(0, 30))
        self.input_velocity_back.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_back.setAlignment(Qt.AlignCenter)
        self.input_velocity_back.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_back.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_back.setProperty("showGroupSeparator", False)
        self.input_velocity_back.setMaximum(1.000000000000000)
        self.input_velocity_back.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.input_velocity_back)

        self.input_velocity_up = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_up.setObjectName(u"input_velocity_up")
        sizePolicy4.setHeightForWidth(self.input_velocity_up.sizePolicy().hasHeightForWidth())
        self.input_velocity_up.setSizePolicy(sizePolicy4)
        self.input_velocity_up.setMinimumSize(QSize(0, 30))
        self.input_velocity_up.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_up.setAlignment(Qt.AlignCenter)
        self.input_velocity_up.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_up.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_up.setProperty("showGroupSeparator", False)
        self.input_velocity_up.setMaximum(1.000000000000000)
        self.input_velocity_up.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.input_velocity_up)

        self.input_velocity_down = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_down.setObjectName(u"input_velocity_down")
        sizePolicy4.setHeightForWidth(self.input_velocity_down.sizePolicy().hasHeightForWidth())
        self.input_velocity_down.setSizePolicy(sizePolicy4)
        self.input_velocity_down.setMinimumSize(QSize(0, 30))
        self.input_velocity_down.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_down.setAlignment(Qt.AlignCenter)
        self.input_velocity_down.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_down.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_down.setProperty("showGroupSeparator", False)
        self.input_velocity_down.setMaximum(1.000000000000000)
        self.input_velocity_down.setSingleStep(0.050000000000000)

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.input_velocity_down)

        self.input_velocity_turn_left = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_turn_left.setObjectName(u"input_velocity_turn_left")
        sizePolicy4.setHeightForWidth(self.input_velocity_turn_left.sizePolicy().hasHeightForWidth())
        self.input_velocity_turn_left.setSizePolicy(sizePolicy4)
        self.input_velocity_turn_left.setMinimumSize(QSize(0, 30))
        self.input_velocity_turn_left.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_turn_left.setFrame(False)
        self.input_velocity_turn_left.setAlignment(Qt.AlignCenter)
        self.input_velocity_turn_left.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_turn_left.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_turn_left.setProperty("showGroupSeparator", True)
        self.input_velocity_turn_left.setDecimals(1)
        self.input_velocity_turn_left.setMaximum(360.000000000000000)

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.input_velocity_turn_left)

        self.input_velocity_turn_right = QDoubleSpinBox(self.group_continous_motion)
        self.input_velocity_turn_right.setObjectName(u"input_velocity_turn_right")
        sizePolicy4.setHeightForWidth(self.input_velocity_turn_right.sizePolicy().hasHeightForWidth())
        self.input_velocity_turn_right.setSizePolicy(sizePolicy4)
        self.input_velocity_turn_right.setMinimumSize(QSize(0, 30))
        self.input_velocity_turn_right.setCursor(QCursor(Qt.ArrowCursor))
        self.input_velocity_turn_right.setFrame(False)
        self.input_velocity_turn_right.setAlignment(Qt.AlignCenter)
        self.input_velocity_turn_right.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_velocity_turn_right.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_velocity_turn_right.setProperty("showGroupSeparator", True)
        self.input_velocity_turn_right.setDecimals(1)
        self.input_velocity_turn_right.setMaximum(360.000000000000000)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.input_velocity_turn_right)


        self.gridLayout_2.addWidget(self.group_continous_motion, 0, 1, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer, 2, 3, 1, 1)

        self.group_move_distance = QGroupBox(self.scrollAreaWidgetContents)
        self.group_move_distance.setObjectName(u"group_move_distance")
        sizePolicy3.setHeightForWidth(self.group_move_distance.sizePolicy().hasHeightForWidth())
        self.group_move_distance.setSizePolicy(sizePolicy3)
        self.group_move_distance.setMinimumSize(QSize(0, 300))
        self.group_move_distance.setMaximumSize(QSize(300, 350))
        self.group_move_distance.setCheckable(True)
        self.formLayout_2 = QFormLayout(self.group_move_distance)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.label = QLabel(self.group_move_distance)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label)

        self.label_2 = QLabel(self.group_move_distance)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_2)

        self.label_3 = QLabel(self.group_move_distance)
        self.label_3.setObjectName(u"label_3")
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QSize(0, 0))
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.label_3)

        self.label_4 = QLabel(self.group_move_distance)
        self.label_4.setObjectName(u"label_4")
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QSize(0, 0))
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.label_4)

        self.label_5 = QLabel(self.group_move_distance)
        self.label_5.setObjectName(u"label_5")
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QSize(0, 0))
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.label_5)

        self.label_6 = QLabel(self.group_move_distance)
        self.label_6.setObjectName(u"label_6")
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.formLayout_2.setWidget(5, QFormLayout.LabelRole, self.label_6)

        self.label_13 = QLabel(self.group_move_distance)
        self.label_13.setObjectName(u"label_13")
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QSize(0, 0))

        self.formLayout_2.setWidget(6, QFormLayout.LabelRole, self.label_13)

        self.label_14 = QLabel(self.group_move_distance)
        self.label_14.setObjectName(u"label_14")
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QSize(0, 0))

        self.formLayout_2.setWidget(7, QFormLayout.LabelRole, self.label_14)

        self.input_distance_forward = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_forward.setObjectName(u"input_distance_forward")
        sizePolicy4.setHeightForWidth(self.input_distance_forward.sizePolicy().hasHeightForWidth())
        self.input_distance_forward.setSizePolicy(sizePolicy4)
        self.input_distance_forward.setMinimumSize(QSize(0, 30))
        self.input_distance_forward.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_forward.setFrame(False)
        self.input_distance_forward.setAlignment(Qt.AlignCenter)
        self.input_distance_forward.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_forward.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_forward.setProperty("showGroupSeparator", False)
        self.input_distance_forward.setDecimals(1)
        self.input_distance_forward.setMaximum(15.000000000000000)
        self.input_distance_forward.setSingleStep(0.500000000000000)
        self.input_distance_forward.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.input_distance_forward)

        self.input_distance_left = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_left.setObjectName(u"input_distance_left")
        sizePolicy4.setHeightForWidth(self.input_distance_left.sizePolicy().hasHeightForWidth())
        self.input_distance_left.setSizePolicy(sizePolicy4)
        self.input_distance_left.setMinimumSize(QSize(0, 30))
        self.input_distance_left.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_left.setFrame(False)
        self.input_distance_left.setAlignment(Qt.AlignCenter)
        self.input_distance_left.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_left.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_left.setProperty("showGroupSeparator", False)
        self.input_distance_left.setDecimals(1)
        self.input_distance_left.setMaximum(15.000000000000000)
        self.input_distance_left.setSingleStep(0.500000000000000)
        self.input_distance_left.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.input_distance_left)

        self.input_distance_right = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_right.setObjectName(u"input_distance_right")
        sizePolicy4.setHeightForWidth(self.input_distance_right.sizePolicy().hasHeightForWidth())
        self.input_distance_right.setSizePolicy(sizePolicy4)
        self.input_distance_right.setMinimumSize(QSize(0, 30))
        self.input_distance_right.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_right.setFrame(False)
        self.input_distance_right.setAlignment(Qt.AlignCenter)
        self.input_distance_right.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_right.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_right.setProperty("showGroupSeparator", False)
        self.input_distance_right.setDecimals(1)
        self.input_distance_right.setMaximum(15.000000000000000)
        self.input_distance_right.setSingleStep(0.500000000000000)
        self.input_distance_right.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.input_distance_right)

        self.input_distance_back = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_back.setObjectName(u"input_distance_back")
        sizePolicy4.setHeightForWidth(self.input_distance_back.sizePolicy().hasHeightForWidth())
        self.input_distance_back.setSizePolicy(sizePolicy4)
        self.input_distance_back.setMinimumSize(QSize(0, 30))
        self.input_distance_back.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_back.setFrame(False)
        self.input_distance_back.setAlignment(Qt.AlignCenter)
        self.input_distance_back.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_back.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_back.setProperty("showGroupSeparator", False)
        self.input_distance_back.setDecimals(1)
        self.input_distance_back.setMaximum(15.000000000000000)
        self.input_distance_back.setSingleStep(0.500000000000000)
        self.input_distance_back.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.input_distance_back)

        self.input_distance_up = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_up.setObjectName(u"input_distance_up")
        sizePolicy4.setHeightForWidth(self.input_distance_up.sizePolicy().hasHeightForWidth())
        self.input_distance_up.setSizePolicy(sizePolicy4)
        self.input_distance_up.setMinimumSize(QSize(0, 30))
        self.input_distance_up.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_up.setFrame(False)
        self.input_distance_up.setAlignment(Qt.AlignCenter)
        self.input_distance_up.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_up.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_up.setProperty("showGroupSeparator", False)
        self.input_distance_up.setDecimals(1)
        self.input_distance_up.setMaximum(15.000000000000000)
        self.input_distance_up.setSingleStep(0.500000000000000)
        self.input_distance_up.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.input_distance_up)

        self.input_distance_down = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_down.setObjectName(u"input_distance_down")
        sizePolicy4.setHeightForWidth(self.input_distance_down.sizePolicy().hasHeightForWidth())
        self.input_distance_down.setSizePolicy(sizePolicy4)
        self.input_distance_down.setMinimumSize(QSize(0, 30))
        self.input_distance_down.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_down.setFrame(False)
        self.input_distance_down.setAlignment(Qt.AlignCenter)
        self.input_distance_down.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_down.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_down.setProperty("showGroupSeparator", False)
        self.input_distance_down.setDecimals(1)
        self.input_distance_down.setMaximum(15.000000000000000)
        self.input_distance_down.setSingleStep(0.500000000000000)
        self.input_distance_down.setStepType(QAbstractSpinBox.DefaultStepType)

        self.formLayout_2.setWidget(5, QFormLayout.FieldRole, self.input_distance_down)

        self.input_distance_turn_left = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_turn_left.setObjectName(u"input_distance_turn_left")
        sizePolicy4.setHeightForWidth(self.input_distance_turn_left.sizePolicy().hasHeightForWidth())
        self.input_distance_turn_left.setSizePolicy(sizePolicy4)
        self.input_distance_turn_left.setMinimumSize(QSize(0, 30))
        self.input_distance_turn_left.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_turn_left.setFrame(False)
        self.input_distance_turn_left.setAlignment(Qt.AlignCenter)
        self.input_distance_turn_left.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_turn_left.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_turn_left.setProperty("showGroupSeparator", True)
        self.input_distance_turn_left.setDecimals(1)
        self.input_distance_turn_left.setMaximum(360.000000000000000)

        self.formLayout_2.setWidget(6, QFormLayout.FieldRole, self.input_distance_turn_left)

        self.input_distance_turn_right = QDoubleSpinBox(self.group_move_distance)
        self.input_distance_turn_right.setObjectName(u"input_distance_turn_right")
        sizePolicy4.setHeightForWidth(self.input_distance_turn_right.sizePolicy().hasHeightForWidth())
        self.input_distance_turn_right.setSizePolicy(sizePolicy4)
        self.input_distance_turn_right.setMinimumSize(QSize(0, 30))
        self.input_distance_turn_right.setCursor(QCursor(Qt.ArrowCursor))
        self.input_distance_turn_right.setFrame(False)
        self.input_distance_turn_right.setAlignment(Qt.AlignCenter)
        self.input_distance_turn_right.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.input_distance_turn_right.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.input_distance_turn_right.setProperty("showGroupSeparator", True)
        self.input_distance_turn_right.setDecimals(1)
        self.input_distance_turn_right.setMaximum(360.000000000000000)

        self.formLayout_2.setWidget(7, QFormLayout.FieldRole, self.input_distance_turn_right)


        self.gridLayout_2.addWidget(self.group_move_distance, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout.addWidget(self.scrollArea, 0, 2, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CrazyFlie Simulator Control", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.group_button.setTitle(QCoreApplication.translate("MainWindow", u"Controls", None))
        self.button_disconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.button_connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.button_takeoff.setText(QCoreApplication.translate("MainWindow", u"Takeoff", None))
        self.button_fly.setText(QCoreApplication.translate("MainWindow", u"Fly", None))
        self.button_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.button_hover.setText(QCoreApplication.translate("MainWindow", u"Hover", None))
        self.button_land.setText(QCoreApplication.translate("MainWindow", u"Land", None))
        self.group_plot.setTitle(QCoreApplication.translate("MainWindow", u"Motion History", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Log Book", None))
        self.group_telemetry.setTitle(QCoreApplication.translate("MainWindow", u"Telemetry", None))
        self.group_continous_motion.setTitle(QCoreApplication.translate("MainWindow", u"Continuous Motion", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Turn Left", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Turn Right", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_forward.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_forward.setSpecialValueText("")
        self.input_velocity_forward.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_left.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_left.setSpecialValueText("")
        self.input_velocity_left.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_right.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_right.setSpecialValueText("")
        self.input_velocity_right.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_back.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_back.setSpecialValueText("")
        self.input_velocity_back.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_up.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_up.setSpecialValueText("")
        self.input_velocity_up.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
#if QT_CONFIG(tooltip)
        self.input_velocity_down.setToolTip(QCoreApplication.translate("MainWindow", u"Max 1 m/s", None))
#endif // QT_CONFIG(tooltip)
        self.input_velocity_down.setSpecialValueText("")
        self.input_velocity_down.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
        self.input_velocity_turn_left.setSuffix(QCoreApplication.translate("MainWindow", u" \u00b0/s", None))
        self.input_velocity_turn_right.setSuffix(QCoreApplication.translate("MainWindow", u" \u00b0/s", None))
        self.group_move_distance.setTitle(QCoreApplication.translate("MainWindow", u"Move Distance", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Turn Left", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Turn Right", None))
#if QT_CONFIG(tooltip)
        self.input_distance_forward.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_forward.setSpecialValueText("")
        self.input_distance_forward.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
#if QT_CONFIG(tooltip)
        self.input_distance_left.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_left.setSpecialValueText("")
        self.input_distance_left.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
#if QT_CONFIG(tooltip)
        self.input_distance_right.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_right.setSpecialValueText("")
        self.input_distance_right.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
#if QT_CONFIG(tooltip)
        self.input_distance_back.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_back.setSpecialValueText("")
        self.input_distance_back.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
#if QT_CONFIG(tooltip)
        self.input_distance_up.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_up.setSpecialValueText("")
        self.input_distance_up.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
#if QT_CONFIG(tooltip)
        self.input_distance_down.setToolTip(QCoreApplication.translate("MainWindow", u"Max 15 m", None))
#endif // QT_CONFIG(tooltip)
        self.input_distance_down.setSpecialValueText("")
        self.input_distance_down.setSuffix(QCoreApplication.translate("MainWindow", u" m ", None))
        self.input_distance_turn_left.setSuffix(QCoreApplication.translate("MainWindow", u" \u00b0", None))
        self.input_distance_turn_right.setSuffix(QCoreApplication.translate("MainWindow", u" \u00b0", None))
    # retranslateUi

